version: "3.5"
services:
  slowloris:
    build: slowloris/
    container_name: slowloris
    volumes:
      - ./slowloris/volumes/:/usr/games/attack
    entrypoint:
      - python3
      - /usr/games/attack/run.py
      - "10"
      - -s 10000
      - -ua
      - ${VICTIM_HOST}

    networks:
      - net

  nginx:
    image: nginx
    container_name: victim
    ports:
      - 8080:80
    volumes:
      - ./victim/volumes/nginx.conf:/etc/nginx/nginx.conf

    networks:
      - net

networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/16