version: "3.5"
services:
  slowloris:
    image: lesterhrenestr/slowloris
    container_name: slowloris
    entrypoint:
      - python3
      - /usr/games/attack/run.py
      - "10"
      - -s 10000
      - -ua
      - ${VICTIM_HOST}

    networks:
      - net

  nginx:
    image: lesterhrenestr/victim
    container_name: victim
    ports:
      - 8080:80

    networks:
      - net

networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/16